CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    spv BIGINT REFERENCES users(id) ON DELETE SET NULL,
    "group" VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS approvals (
    id BIGSERIAL PRIMARY KEY,
    transaction VARCHAR(255) NOT NULL,
    requester BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    approver BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
